name: Build, Push and Deploy

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: davidnguyen7603/coolchatai
          tags: |
            type=sha,format=short  # Luôn tạo tag từ commit SHA
            type=semver,pattern={{version}}  # Tag version nếu có git tag
            type=ref,event=branch  # Tag theo branch name

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to Render
        if: ${{ github.event_name != 'pull_request' }}  # Chỉ deploy khi push thật
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
        run: |
          # Lấy tag đầu tiên từ metadata (ví dụ: sha-d672428)
          FULL_TAG=$(echo "$IMAGE_TAG" | cut -d ',' -f 1)
          
          # Gọi API Render với imageRef chính xác
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"imageRef": "'"$FULL_TAG"'"}'
          
          echo "✅ Triggered deploy image: $FULL_TAG"
